ci:
  autoupdate_schedule: monthly

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 'v4.1.0'
    hooks:
      - id: check-yaml
      - id: trailing-whitespace
        args: ['--markdown-linebreak-ext=md,markdown']
      - id: end-of-file-fixer

  - repo: https://github.com/asottile/reorder_python_imports
    rev: 'v2.6.0'
    hooks:
      - id: reorder-python-imports

  - repo: https://github.com/psf/black
    rev: '21.12b0'
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/flake8
    rev: '4.0.1'
    hooks:
      - id: flake8

  - repo: https://github.com/kynan/nbstripout
    rev: '0.5.0'
    hooks:
      - id: nbstripout
