name: blpd-dev
channels:
  - conda-forge
dependencies:
  - python=3.8
  #
  # used by blpd
  - matplotlib
  - numba
  - numpy
  - scipy
  - xarray
  #
  # example nbs
  - ipywidgets
  - jupyterlab >= 3
  #
  # dev
  - rope
  #
  - pip
  - pip:
      # the package as an editable install
      - '-e .[docs]'
