name: CI

on:
  push:
    branches: [ '*' ]
    paths: [ '**.py', '**.ipynb', '.github/workflows/ci.yml' ]
  pull_request:
    branches: [ master ]
    paths: [ '**.py', '**.ipynb', '.github/workflows/ci.yml' ]

jobs:
  examples:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install the package
        run: |
          set -xe
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install .

      - name: Run the examples
        run: |
          set -xe
          python -m pip install notebook ipywidgets
          cd examples
          for f in *.ipynb; do
            jupyter nbconvert --to notebook --execute $f
          done
